pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    
        stage('Build') {
            steps {
                echo 'Building stage'
            }
        }
    
        stage('Deploy') {
            steps {
                echo 'Deployment stage'
            }
        }
    
        stage('Test') {
            steps {
                echo 'Testing stage'
            }
        }
    } 
        
}
